### ISSUE TITLE
DtlTrader - Red in game console - Not working

### ISSUE THREAD

**Issue by MCMaricopaAZ** [Dandielo/dtlCore#1]
I downloaded from mcspigot.com - DtlTrader 3.4.3
I copied the two jar files to the plugins directory and restarted my server.

These are the only two jars I found in the download.
dtlCore(1.9).jar
dtlTraders.jar

Host: Fluctis
Server:  MC 1.9.2 spigot

**Current Plugins:
Lockette,
Valut
ChestRegen
PermissionsEx
Multiverse-Core
Multiverse-Portals
EnjinMinecraftPlugin
Citizens2

**Comment by MCMaricopaAZ** [comment]
Additional notes.
I am NOT using MySql  (not sure if this matters)

**Comment by MCMaricopaAZ** [comment]
I added Sentry.jar and it works   I tried Blacksmith but it doesn't work.

**Comment by MCMaricopaAZ** [comment]
Ah, Ha!   I'm missing an Economy plugin.   I'm adding Essentials for the "Economy" component.

**Comment by MCMaricopaAZ** [comment]
BINGO!   That was it.   The "Essentials" plugin turned the DtlTrader Plugin green.   Trying it now.

**Comment by MCMaricopaAZ** [comment]
I had to un-install Essentials and I tried EconomyCraft and it's all working.  Sentry is working, DtlTrader is working and Blacksmith.  :)  Yeah!

**Comment by Dandielo** [comment]
Sorry for not responding for your issue, glad you could figure it out, however I wont really be any helpful with Bukkit plugin related issue because I dont develop them anymore, I do not find it interesting and/or entraining thus all mu Bukkit projects are abandoned. 

Maybe some1 can take this plugin and make it awesome again, but this wont be me, sorry :(
